name: Actions Runner Controller Demo
on:
  workflow_dispatch:

jobs:
  Explore-GitHub-Actions:
    runs-on: arc-runner-set
    steps:
      - name: Check OS Version
        run: |
          lsb_release -a
        shell: bash
        
      - name: Install Docker
        run: |
          # Add Docker's official GPG key:
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends ca-certificates curl software-properties-common
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg

          # Add the Docker repository to APT sources:
          echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

          sudo apt-get update
          sudo apt-get install -y docker-ce docker-ce-cli containerd.io
          docker -v
        shell: bash

      - name: Install Node.js
        run: |
          # Install Node.js using NodeSource repository
          curl -fsSL https://deb.nodesource.com/gpgkey/nodesource.gpg.key | sudo gpg --dearmor -o /usr/share/keyrings/nodesource-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/nodesource-archive-keyring.gpg] https://deb.nodesource.com/node_14.x $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/nodesource.list > /dev/null

          sudo apt-get update
          sudo apt-get install -y nodejs
          node -v
          npm -v
        shell: bash

      - name: Checkout Code
        uses: actions/checkout@v2

      - name: List Files
        run: |
          ls
          docker -v
              
          
        
          

      - uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: get pods
