name: Actions Runner Controller Demo
on:
  workflow_dispatch:

jobs:
  Explore-GitHub-Actions:
    # You need to use the INSTALLATION_NAME from the previous step
    runs-on: ubuntu-latest
    steps:
    - run: echo "🎉 This job uses runner scale set runners!"
    - name: Install update
      run: |
        sudo apt update
        sudo apt upgrade
    - name: Install Nodejs
      run: | 
        sudo apt install nodejs
        node -v
    - uses: actions/checkout@v1
    - run: ls
    - uses: actions-hub/kubectl@master
      env:
        KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
      with:
        args: get pods

